version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders_app
    ports:
      - "8080:8080"
      - "50051:50051"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - orders-network

  db:
    image: postgres:15
    container_name: orders_postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - orders-network

  adminer:
    image: adminer
    container_name: orders_adminer
    ports:
      - "8081:8080"
    networks:
      - orders-network

volumes:
  pgdata:

networks:
  orders-network:
    driver: bridge
